config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :accounts do
    resources :transactions
  end

  resources :transactions
  
  resources :imports do
    resources :rules
  end

  resources :parsers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/import.rb
class Import < CouchRest::Model::Base
  REGEXP_RULE = 'REGEXP_RULE'
  STRING_RULE = 'STRING_RULE'
  LUCKY_RULE = 'LUCKY_RULE'
  
  property :label,  String
  property :parser,  String
  property :rules, array: true do
    property :r_type, String
    property :token, String
    property :description, String
    property :account_from, String
    property :account_to, String
  end
  
  design do
    view :by_label
  end
end

app/controllers/imports_controller.rb
class ImportsController < ApplicationController
  def index
    @imports = Import.all
  end

  def new
    @import = Import.new
    @parsers = Dir[Rails.root.join('lib', 'parser', '*.rb')].map {|parser_file| File.basename(parser_file, ".rb").classify}
  end
  
  def create
    import = Import.new
    import.label = params['label']
    import.parser = params['parser']
    import.save
    redirect_to imports_path
  end
  
  def edit
    @import = Import.find(params['id'])
    @parsers = Dir[Rails.root.join('lib', 'parser', '*.rb')].map {|parser_file| File.basename(parser_file, ".rb").classify}
  end
  
  def update
    import = Import.find(params['id'])
    import.label = params['label']
    import.parser = params['parser']
    import.save
    redirect_to imports_path
  end
end

app/helpers/imports_helper.rb
module ImportsHelper
end

app/views/imports/_form.html.erb
<div class="form-group">
  <label for="label">Etichetta</label>
  <input type="text" class="form-control" id="label" name="label" value="<%= @import.label %>">
</div>
<div class="form-group">
  <label for="parser">Classe del parser</label>
  <select class="form-control" id="parser" name="parser">
    <option value=""  <%=  @import.parser.nil? ? "selected='selected'" : "" %>>-- Scegli --</option>
    <% @parsers.each do |parser| -%>
    <option value="<%= parser %>"  <%= parser ==  @import.parser ? "selected='selected'" : "" %>><%= parser %></option>
    <% end -%>
  </select>
</div>
<button type="submit" class="btn btn-default">Salva</button>
 
 

app/views/imports/edit.html.erb
<div class="main_container page import" id="edit_import">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Modifica tipo di import</h1>
      <%= form_tag(import_path(@import.id), method: :put) do -%>
        <%= render 'form' %>
      <% end %>
    </div>
  </div>
</div>
 
 
 

app/views/imports/index.html.erb
<div class="main_container page" id="imports">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Import da file <a href="<%= new_import_path %>" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Nuovo tipo di import</a></h1>
      <div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="edit"></th>
              <th>Etichetta</th>
              <th>Classe per l'import</th>
              <th class="rules">Regole</th>
            </tr>
          </thead>
          <tbody>
            <% @imports.each do |import| %>
            <tr>
              <td><a href="<%= edit_import_path(import.id) %>" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-pencil"></span></a></td>
              <td><%= import.label %></td>
              <td><%= import.parser %></td>
              <td>
                <a href="<%= import_rules_path(import.id) %>" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-list-alt"></span></a>
                <a href="<%= new_import_rule_path(import.id) %>" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-plus"></span></a>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>
 

app/views/imports/new.html.erb
<div class="main_container page import" id="new_import">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Nuovo tipo di import</h1>
      <%= form_tag(imports_path, method: :post) do -%>
        <%= render 'form' %>
      <% end %>
    </div>
  </div>
</div>
 
 