config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :accounts do
    resources :transactions
  end

  resources :transactions
  
  resources :imports do
    resources :rules
  end

  resources :parsers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
    @account = Account.find(params['account_id'])
    @transactions = Transaction.by_account_to_id_and_dt.startkey([@account.id, Time.local(2017,1,1).to_i]).endkey([@account.id, Time.now.to_i]).all
    if(@account.atype == Account::DEPOSIT)
      @transactions += Transaction.by_account_from_id_and_dt.startkey([@account.id, Time.local(2017,1,1).to_i]).endkey([@account.id, Time.now.to_i]).all
      @transactions.sort_by! {|t| t.dt}
    end
  end
  
  def new
    prepare_accounts
    @account = Account.find(params['account_id'])
    @transaction = Transaction.new
    @transaction.account_to = @account
    @transaction.dt = Time.now.to_i
  end
  
  def create
    @transaction = Transaction.new
    update_transaction
    respond_to do |format|
      format.html {redirect_to accounts_path}
      format.json { render json: {success: true, transaction_id: @transaction.id} }
    end
    
  end
  
  def edit
    prepare_accounts
    @transaction = Transaction.find(params['id'])
  end
 
  def update
    @transaction = Transaction.find(params['id'])
    update_transaction
    redirect_to accounts_path
  end

  def destroy
    @transaction = Transaction.find(params['id'])
    @transaction.destroy
    redirect_to accounts_path
  end

  private

  def update_transaction
    @transaction.account_from = Account.find(params['account_from'])
    @transaction.account_to = Account.find(params['account_to'])
    @transaction.description = params['description']
    @transaction.note = params['note']
    @transaction.amount = params['amount'].to_f
    @transaction.dt = params['dt'].to_i
    @transaction.save
  end
  
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_form.html.erb
<div class="form-group">
  <label for="account_in">Da</label>
  <select class="form-control" id="account_from" name="account_from">
    <option value=""  <%=  @transaction.account_from.nil? ? "selected='selected'" : "" %>>-- Scegli --</option>
    <% @accounts[Account::DEPOSIT].each do |account| -%>
    <option value="<%= account.id %>"  <%= account == @transaction.account_from ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
    <% @accounts[Account::INCOMES].each do |account| -%>
    <option value="<%= account.id %>"  <%= account == @transaction.account_from ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
    <% @accounts[Account::EXPENSES].each do |account| -%>
    <option value="<%= account.id %>"  <%= account == @transaction.account_from ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
  </select>
</div>
<div class="form-group">
  <label for="account_from">A</label>
  <select class="form-control" id="account_to" name="account_to">
    <option value=""  <%=  @transaction.account_to.nil? ? "selected='selected'" : "" %>>-- Scegli --</option>
    <% @accounts[Account::DEPOSIT].each do |account| -%>
    <option value="<%= account.id %>"  <%= account == @transaction.account_to ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
    <% @accounts[Account::EXPENSES].each do |account| -%>
    <option value="<%= account.id %>"  <%= account == @transaction.account_to ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
  </select>
</div>
<div class="form-group">
  <label for="description">Descrizione</label>
  <input type="text" class="form-control" id="description" name="description" value="<%= @transaction.description %>">
</div>
<div class="form-group">
  <label for="amount">Ammontare</label>
  <input type="text" class="form-control" id="amount" name="amount" value="<%= @transaction.amount %>">
</div>
<div class="form-group">
  <label for="note">Note</label>
  <textarea class="form-control" id="note" name="note"><%= @transaction.note %></textarea>
</div>
<input type='hidden' class="form-control" name="dt" id="hidden_dt" data-current="<%= @transaction.dt %>" />
<div style="overflow:hidden;">
  <div class="form-group">
    <label for="dt">Data/Ora</label>
    <div class="row">
      <div class="col-md-8">
        <div id="dt">
        </div>
      </div>
    </div>
  </div>
</div>
<button type="submit" class="btn btn-default">Salva</button>
 

app/views/transactions/edit.html.erb
<div class="main_container page transaction" id="new_transaction">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Modifica transazione</h1>
      <%= form_tag(transaction_path(@transaction.id), method: :put) do -%>
        <%= render 'form' %>
      <% end %>
    </div>
  </div>
</div>
 
 

app/views/transactions/index.html.erb
<div class="main_container page" id="transactions">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Transazioni per <i><%= @account.label %></i> <a href="<%= new_account_transaction_path(@account.id) %>" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Nuova transazione</a></h1>
      <div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="dt">Data</th>
              <th class="description">Descrizione</th>
              <th class="amount">Ammontare</th>
              <% if(@account.atype == Account::DEPOSIT) %>
              <% total = 0 %>
              <th class="amount">Progressivo</th>
              <% end %>
              <th class="actions"></th>
            </tr>
          </thead>
          <tbody>
            <% @transactions.each do |transaction| %>
            <tr>
              <td><%= Time.at(transaction.dt).strftime("%d/%m/%Y %H:%M") %></td>
              <td><%= transaction.description %></td>
              <td><%= transaction.amount %></td>
              <% if(@account.atype == Account::DEPOSIT) %>
              <% total += (@account.id == transaction.account_to_id ? transaction.amount : -transaction.amount) %>
              <td><%= total %></th>
              <% end %>
              <td>
	        <a href="<%= edit_transaction_path(transaction.id) %>" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-pencil"></span></a>
		<%= link_to( transaction_path(transaction.id), method: :delete, data: {confirm: "Sicuro ?"}, class: 'btn btn-danger' ) do %>
	        <span class='glyphicon glyphicon-trash'></span>
         	<% end %>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/transactions/new.html.erb
<div class="main_container page transaction" id="new_transaction">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Nuova transazione</h1>
      <%= form_tag(transactions_path, method: :post) do -%>
        <%= render 'form' %>
      <% end %>
    </div>
  </div>
</div>
 