config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :accounts do
    resources :transactions
  end

  resources :transactions
  
  resources :imports do
    resources :rules
  end

  resources :parsers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/rules_controller.rb
class RulesController < ApplicationController
  def index
    @import = Import.find(params['import_id'])
    @accounts = Hash[Account.all.map{|account| [account.id, account.label]}]
  end
  
  def new
    @import = Import.find(params['import_id'])
    @rule = {}
    @accounts = Account.by_atype_and_label
  end
  
  def create
    @import = Import.find(params['import_id'])
    @import.rules << {
      r_type: params["r_type"],
      token: params["token"],
      description: params["description"],
      account_from: params["account_from"],
      account_to: params["account_to"]
    }
    @import.save
    redirect_to import_rules_path(@import.id)
  end
  
  def edit
    @import = Import.find(params['import_id'])
    @rule = @import.rules[params['id'].to_i]
    @accounts = Account.by_atype_and_label
  end
  
  def update
    @import = Import.find(params['import_id'])
    rule = @import.rules[params['id'].to_i]
    rule.r_type = params["r_type"]
    rule.token = params["token"]
    rule.description = params["description"]
    rule.account_from = params["account_from"]
    rule.account_to = params["account_to"]
    @import.save
    redirect_to import_rules_path(@import.id)
  end
end

app/helpers/rules_helper.rb
module RulesHelper
end

app/views/rules/_form.html.erb
<div class="form-group">
  <label for="r_type">Tipo di regola</label>
  <select class="form-control" id="r_type" name="r_type">
    <option value=""  <%= @rule[:r_type].nil? ? "selected='selected'" : "" %>>-- Scegli --</option>
    <% [Import::REGEXP_RULE, Import::STRING_RULE, Import::LUCKY_RULE ].each do |r_type| -%>
    <option value="<%= r_type %>"  <%= @rule[:r_type] ==  r_type ? "selected='selected'" : "" %>><%= r_type %></option>
    <% end -%>
  </select>
</div>
<div class="form-group">
  <label for="token">Token</label>
  <input type="text" class="form-control" id="token" name="token" value="<%= @rule[:token] %>">
</div>
<div class="form-group">
  <label for="description">Descrizione</label>
  <input type="text" class="form-control" id="description" name="description" value="<%= @rule[:description] %>">
</div>
<div class="form-group">
  <label for="account_in">Da</label>
  <select class="form-control" id="account_from" name="account_from">
    <option value=""  <%=  @rule[:account_from].nil? ? "selected='selected'" : "" %>>-- Scegli --</option>
    <% @accounts.each do |account| -%>
    <option value="<%= account.id %>"  <%= account.id == @rule[:account_from] ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
  </select>
</div>
<div class="form-group">
  <label for="account_out">A</label>
  <select class="form-control" id="account_to" name="account_to">
    <option value=""  <%=  @rule[:account_to].nil? ? "selected='selected'" : "" %>>-- Scegli --</option>
    <% @accounts.each do |account| -%>
    <option value="<%= account.id %>"  <%= account.id == @rule[:account_to] ? "selected='selected'" : "" %>><%= account.label %></option>
    <% end -%>
  </select>
</div>
<button type="submit" class="btn btn-default">Salva</button>
 

app/views/rules/edit.html.erb
<div class="main_container page rule" id="edit_rule">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Modifica regola per il tipo di import <%= @import.label %></h1>
      <%= form_tag(import_rule_path(@import.id, params['id']), method: :put) do -%>
        <%= render 'form' %>
      <% end %>
    </div>
  </div>
</div>
 
 
 

app/views/rules/index.html.erb
<div class="main_container page" id="rules">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Regole per l'import <i><%= @import.label%></i> <a href="<%= new_import_rule_path(@import.id) %>" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Nuova regola</a></h1>
      <div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="edit"></th>
              <th>Tipo</th>
              <th>Token</th>
              <th>Descrizione</th>
              <th>Da</th>
              <th>A</th>
            </tr>
          </thead>
          <tbody>
            <% @import.rules.each_with_index do |rule, idx| %>
            <tr>
              <td><a href="<%= edit_import_rule_path(@import.id, idx) %>" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-pencil"></span></a></td>
              <td><%= rule.r_type %></td>
              <td><%= rule.token %></td>
              <td><%= rule.description %></td>
              <td><%= @accounts[rule.account_from] %></td>
              <td><%= @accounts[rule.account_to] %></td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/rules/new.html.erb
<div class="main_container page transaction" id="new_rule">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Nuova regola per il tipo di import <%= @import.label %></h1>
      <%= form_tag(import_rules_path(@import.id), method: :post) do -%>
        <%= render 'form' %>
      <% end %>
    </div>
  </div>
</div>
 
 