config/routes.rb
Rails.application.routes.draw do

  root 'dashboard#index'

  resources :accounts do
    resources :transactions
  end

  resources :transactions
  
  resources :imports do
    resources :rules
  end

  resources :parsers

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/account.rb
class Account < CouchRest::Model::Base
  DEPOSIT = 'DEPOSIT'
  EXPENSES = 'EXPENSES'
  INCOMES = 'INCOMES'

  property :label,  String
  property :atype,  String

  collection_of :tags

  timestamps!

  design do
    view :by_code
    view :by_label
    view :by_atype
    view :by_atype_and_label
  end
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  def index
    @accounts = Account.by_atype_and_label
    amounts_from = Hash[Transaction.amounts_by_account_from.reduce.group_level(1).rows.map{|a| a.values}]
    amounts_to = Hash[Transaction.amounts_by_account_to.reduce.group_level(1).rows.map{|a| a.values}]
    @amounts = amounts_from.merge(amounts_to){|key, fromval, toval| fromval + toval}
    @tags = Hash[Tag.all.map{|tag| [tag.id, tag.name]}]
  end

  def edit
    @account = Account.find(params[:id])
  end

  def create
    account = Account.new
    save_account(account)
    redirect_to accounts_path
  end
  
  def update
    account = Account.find(params[:id])
    save_account(account)
    redirect_to accounts_path
  end
  
private

  def save_account(account)
    account.label = params[:label]
    account.atype = params[:atype]
    account.tags = []
    unless(params[:tags].nil? || params[:tags].empty?)
      params[:tags].each do |tag_id|
        account.tags << Tag.find(tag_id)
      end
    end
    unless(params[:new_tags].nil? || params[:new_tags].empty?)
      params[:new_tags].split(",").each do |name|
        account.tags << Tag.create(name: name.strip)
      end
    end
    account.save
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/edit.html.erb
<div class="main_container page" id="new_account">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Modifica conto</h1>
        <%= form_tag(account_path(@account.id), method: :put) -%>
          <div class="form-group">
            <label for="label">Etichetta</label>
            <input type="text" class="form-control" id="label" name="label" value="<%= @account.label%>">
          </div>
          <div class="form-group">
            <label for="atype">Tipo</label>
            <select class="form-control" id="atype" name="atype">
              <% [Account::DEPOSIT, Account::EXPENSES, Account::INCOMES].each do |atype| -%>
              <option value="<%= atype %>"  <%= @account.atype == atype ? "selected='selected'" : "" %>><%= t atype %></option>
              <% end -%>
            </select>
          </div>
          <label>Tags</label>
          <% Tag.by_name.each do |tag|%>
          <label class="checkbox-inline">
            <input type="checkbox" name="tags[]" value="<%= tag.id%>" <%= @account.tags.map{|t| t.name}.join(",").include?(tag.name) ? "checked='checked'" : "" %>> <%= tag.name %>
          </label>
          <% end %>
          <div class="form-group">
            <label for="new_tags">Nuovi tag</label>
            <input type="text" class="form-control" id="new_tags" name="new_tags">
          </div>
          <button type="submit" class="btn btn-default">Salva</button>
        </form>
    </div>
  </div>
</div>

app/views/accounts/index.html.erb
<div class="main_container page" id="accounts">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">
        Conti
        <a href="<%= new_account_path %>" class="btn btn-primary"><span class="glyphicon glyphicon-plus"></span> Nuovo conto</a>
        <a href="<%= new_parser_path %>" class="btn btn-primary"><span class="glyphicon glyphicon-paste"></span> Importa transazioni</a>
      </h1>
      <div>
        <table class="table table-striped">
          <thead>
            <tr>
              <th class="edit"></th>
              <th>Etichetta</th>
              <th>Tags</th>
              <th class="type">Tipo</th>
              <th class="balance">Saldo</th>
              <th class="transactions">Transazioni</th>
            </tr>
          </thead>
          <tbody>
            <% @accounts.each do |account| %>
            <tr>
              <td><a href="<%= edit_account_path(account.id) %>" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-pencil"></span></a></td>
              <td><%= account.label %></td>
              <td><%= account.tag_ids.map{|tag_id| @tags[tag_id]}.join(",") %></td>
              <td class="type_<%= account.atype.downcase %>"><%= t account.atype %></td>
              <td class="balance"><%= number_to_currency(@amounts[account.id], unit: "€", separator: ",", delimiter: ".", format: "%n %u") %></td>
              <td>
                <a href="<%= account_transactions_path(account.id) %>" class="btn btn-sm btn-default"><span class="glyphicon glyphicon-list-alt"></span></a>
                <a href="<%= new_account_transaction_path(account.id) %>" class="btn btn-sm btn-primary"><span class="glyphicon glyphicon-plus"></span></a>
              </td>
            </tr>
            <% end %>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</div>

app/views/accounts/new.html.erb
<div class="main_container page" id="new_account">
  <div class="section section_even">
    <div class="container">
      <h1 class="title">Nuovo conto</h1>
        <%= form_tag(accounts_path, method: :post) -%>
          <div class="form-group">
            <label for="label">Etichetta</label>
            <input type="text" class="form-control" id="label" name="label">
          </div>
          <div class="form-group">
            <label for="atype">Tipo</label>
            <select class="form-control" id="atype" name="atype">
              <% [Account::DEPOSIT, Account::EXPENSES, Account::INCOMES ].each do |atype| -%>
              <option value="<%= atype %>"><%= t atype %></option>
              <% end -%>
            </select>
          </div>
          <label>Tags</label>
          <% Tag.by_name.each do |tag|%>
          <label class="checkbox-inline">
            <input type="checkbox" name="tags[]" value="<%= tag.id%>"> <%= tag.name %>
          </label>
          <% end %>
          <div class="form-group">
            <label for="new_tags">Nuovi tag</label>
            <input type="text" class="form-control" id="new_tags" name="new_tags">
          </div>
          <button type="submit" class="btn btn-default">Salva</button>
        </form>
    </div>
  </div>
</div>